
[project]
name = "lisa"
description = ""
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = [
  { contract_id = "SP21YTSM60CAY6D011EZVEVNKXVW8FVZE198XEFFP.pox4-fast-pool-v3" },
  { contract_id = "SP001SFSMC2ZY76PD4M68P3WGX154XCH7NE3TYMX.pox4-pools" },
  { contract_id = "SM26NBC8SFHNW4P1Y4DFH27974P56WN86C92HPEHH.lisa-dao" },
  { contract_id = "SM26NBC8SFHNW4P1Y4DFH27974P56WN86C92HPEHH.boot" },
  { contract_id = "SM26NBC8SFHNW4P1Y4DFH27974P56WN86C92HPEHH.treasury" },
  { contract_id = "SM26NBC8SFHNW4P1Y4DFH27974P56WN86C92HPEHH.strategy-trait" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.lip001" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.lip002" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.lip003" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.lip004" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.li-stx-mint-nft" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.li-stx-burn-nft" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.lqstx-mint-endpoint-v2-01" },
  { contract_id = "SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.executor-dao" }  
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.lqstx-mint-endpoint-v2-01" },
  { contract_id = "SPGAB1P3YV109E22KXFJYM63GK0G21BYX50CQ80B.lip005" },
]

[contracts.lip006]
path = "contracts/proposals/lip006.clar"
epoch = 2.5

[contracts.lip007]
path = "contracts/proposals/lip007.clar"
epoch = 2.5
