
[project]
name = "lisa"
description = ""
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = [
  { contract_id = "SP21YTSM60CAY6D011EZVEVNKXVW8FVZE198XEFFP.pox4-fast-pool-v3" },
  { contract_id = "SP001SFSMC2ZY76PD4M68P3WGX154XCH7NE3TYMX.pox4-pools" },
  { contract_id = "SM26NBC8SFHNW4P1Y4DFH27974P56WN86C92HPEHH.lisa-dao" },
  { contract_id = "SM26NBC8SFHNW4P1Y4DFH27974P56WN86C92HPEHH.boot" },
  { contract_id = "SM26NBC8SFHNW4P1Y4DFH27974P56WN86C92HPEHH.treasury" },
  { contract_id = "SM26NBC8SFHNW4P1Y4DFH27974P56WN86C92HPEHH.strategy-trait" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.lip001" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.lip002" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.lip003" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.lip004" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.li-stx-mint-nft" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.li-stx-burn-nft" },
  { contract_id = "SM3KNVZS30WM7F89SXKVVFY4SN9RMPZZ9FX929N0V.lqstx-mint-endpoint-v2-01" },
  { contract_id = "SPGAB1P3YV109E22KXFJYM63GK0G21BYX50CQ80B.lip005" },
  { contract_id = "SP3BQ65DRM8DMTYDD5HWMN60EYC0JFS5NC2V5CWW7.lip006" },
  { contract_id = "SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.executor-dao" },
  { contract_id = "SP102V8P0F7JX67ARQ77WEA3D3CFB5XW39REDT0AM.token-alex" },
  { contract_id = "SP102V8P0F7JX67ARQ77WEA3D3CFB5XW39REDT0AM.alex-staking-v2" },
  { contract_id = "SP102V8P0F7JX67ARQ77WEA3D3CFB5XW39REDT0AM.trait-sip-010" },
  { contract_id = "SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.auto-alex-v2" },
  { contract_id = "SP102V8P0F7JX67ARQ77WEA3D3CFB5XW39REDT0AM.migrate-legacy-v2-wl" },  
  { contract_id = "SP102V8P0F7JX67ARQ77WEA3D3CFB5XW39REDT0AM.executor-dao" }
]

[contracts.lip007]
path = "contracts/proposals/lip007.clar"
epoch = 2.5

[contracts.auto-alex-v3-endpoint]
path = "contracts/extensions/auto-alex-v3-endpoint.clar"
epoch = 2.5

[contracts.auto-alex-v3]
path = "contracts/aux/auto-alex-v3.clar"
epoch = 2.5

[contracts.auto-alex-v3-registry]
path = "contracts/aux/auto-alex-v3-registry.clar"
epoch = 2.5

[contracts.auto-alex-v3-wrapped]
path = "contracts/aux/auto-alex-v3-wrapped.clar"
epoch = 2.5

[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"
epoch = 2.5

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"
epoch = 2.5


[contracts.lisa-dao]
path = "contracts/lisa-dao.clar"
epoch = 2.5

[contracts.mock-boot]
path = "contracts/mocks/tests/mock-boot.clar"
epoch = 2.5

[contracts.legacy-boot]
path = "contracts/mocks/tests/legacy-boot.clar"
epoch = 2.5

[contracts.alex-boot]
path = "contracts/mocks/tests/alex-boot.clar"
epoch = 2.5